# Generated by Django 3.2.9 on 2021-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desayunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desayunos',
            options={'verbose_name': 'desayuno', 'verbose_name_plural': 'desayunos'},
        ),
        migrations.AlterField(
            model_name='desayunos',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='desayunos',
            name='imagen',
            field=models.ImageField(upload_to='desayunos'),
        ),
    ]
