# Generated by Django 3.2.9 on 2021-11-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desayunos', '0002_auto_20211107_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='desayunos',
            name='descripcion',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
