# Generated by Django 3.2.9 on 2021-12-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desayunos', '0003_desayunos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desayunos',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
